import * as pdfjs from './pdf.mjs';
import {defaultIssuer,linesFromItems,parseLines} from './parser.mjs';
pdfjs.GlobalWorkerOptions.workerSrc='./pdf.worker.mjs';
const $=id=>document.getElementById(id);const labels=['Sub Total Ventas','Anticipos','Descuentos','Valor Venta','ISC','IGV','ICBPER','Otros Cargos','Otros Tributos','Monto de redondeo','Importe Total'];
const empty=()=>({...defaultIssuer,type:'Proforma',series:'',client:'',clientDoc:'',date:new Date().toLocaleDateString('es-PE'),payment:'Contado',currency:'SOLES',items:[{qty:1,unit:'UNIDAD',description:'',price:0,amount:0,icbper:0}],totals:Object.fromEntries(labels.map(l=>[l,0])),words:'',free:0,observation:'',establishment:''});let state=empty(),sourceBytes=null,sourceName='',qrBytes=null,qrType='';
function status(t,cls=''){$('status').textContent=t;$('status').className=cls}
function control(container,key,label,choices){let l=document.createElement('label');l.textContent=label;let e=document.createElement(choices?'select':'input');if(choices)for(const s of choices){let o=new Option(s,s);e.add(o)}e.value=state[key]??'';e.dataset.key=key;e.addEventListener('input',()=>{state[key]=e.value;updatePreview();$('calculate').disabled=state.type!=='Proforma';sourceNote()});l.append(e);$(container).append(l)}
function sourceNote(){$('sourceNote').textContent=sourceBytes?'El PDF descargado incluirá el archivo original como anexo.':state.type==='Proforma'?'Proforma comercial. No es comprobante de pago.':'Borrador: debe emitirse en SUNAT o en un sistema autorizado.'}
function render(){ $('fields').replaceChildren();$('issuerfields').replaceChildren();$('totals').replaceChildren();
for(const [k,l,c] of [['type','Tipo de documento',['Factura','Boleta','Proforma']],['series','Serie / número'],['client','Cliente / razón social'],['clientDoc','RUC / DNI del cliente'],['date','Fecha de emisión'],['payment','Forma de pago',['Contado','Crédito']],['currency','Moneda',['SOLES','DÓLARES']],['establishment','Establecimiento del emisor']])control('fields',k,l,c);
for(const [k,l] of [['issuer','Nombre / razón social'],['ruc','RUC del emisor'],['address','Dirección fiscal'],['city','Distrito / provincia / departamento']])control('issuerfields',k,l);
for(const key of labels){let l=document.createElement('label');l.textContent=key;let e=document.createElement('input');e.type='number';e.step='.01';e.value=state.totals[key]??'';e.addEventListener('input',()=>{state.totals[key]=e.value===''?undefined:Number(e.value);updatePreview()});l.append(e);$('totals').append(l)}
let l=document.createElement('label');l.textContent='Valor de operaciones gratuitas';let e=document.createElement('input');e.type='number';e.step='.01';e.value=state.free;e.oninput=()=>state.free=Number(e.value);l.append(e);$('totals').append(l);
$('words').value=state.words;$('observation').value=state.observation;$('calculate').disabled=state.type!=='Proforma';renderItems();updatePreview();sourceNote()}
function renderItems(){$('items').replaceChildren();state.items.forEach((item,i)=>{let tr=document.createElement('tr');for(const k of ['qty','unit','description','price','amount']){let td=document.createElement('td'),e=document.createElement('input');e.setAttribute('aria-label',`${k} ítem ${i+1}`);e.value=item[k];if(['qty','price','amount'].includes(k)){e.type='number';e.step='any';e.min='0'}e.addEventListener('input',()=>{item[k]=e.type==='number'?Number(e.value):e.value;updatePreview()});td.append(e);tr.append(td)}let td=document.createElement('td'),b=document.createElement('button');b.textContent='×';b.setAttribute('aria-label','Eliminar ítem '+(i+1));b.onclick=()=>{state.items.splice(i,1);renderItems();updatePreview()};td.append(b);tr.append(td);$('items').append(tr)})}
const money=n=>Number(n||0).toFixed(2);function updatePreview(){$('previewtype').textContent=state.type==='Factura'?'FACTURA ELECTRÓNICA':state.type==='Boleta'?'BOLETA DE VENTA ELECTRÓNICA':'PROFORMA';$('previewclient').textContent=state.client||'Nombre del cliente';$('previewseries').textContent=state.series||'Número del documento';$('previewtotal').textContent=(state.currency==='SOLES'?'S/ ':'US$ ')+money(state.totals['Importe Total']);$('previewitems').replaceChildren();for(const item of state.items){let row=document.createElement('div');row.className='previewrow';let a=document.createElement('span'),b=document.createElement('span');a.textContent=`${item.qty} ${item.unit} · ${item.description||'Descripción'}`;b.textContent=money(item.amount);row.append(a,b);$('previewitems').append(row)}}
$('words').oninput=e=>state.words=e.target.value;$('observation').oninput=e=>state.observation=e.target.value;
$('blank').onclick=()=>{state=empty();sourceBytes=null;sourceName='';qrBytes=null;$('qr').value='';$('file').value='';$('raw').textContent='Nueva proforma.';render();status('Proforma nueva. Completa los datos y usa Calcular proforma.')};
$('add').onclick=()=>{state.items.push({qty:1,unit:'UNIDAD',description:'',price:0,amount:0,icbper:0});renderItems()};
$('calculate').onclick=()=>{if(state.type!=='Proforma')return;for(const i of state.items)i.amount=Math.round(i.qty*i.price*100)/100;const sub=state.items.reduce((a,i)=>a+i.amount,0);state.totals['Sub Total Ventas']=sub;state.totals['Valor Venta']=sub-(state.totals['Descuentos']||0);state.totals['Importe Total']=Math.round((state.totals['Valor Venta']-(state.totals['Anticipos']||0)+['ISC','IGV','ICBPER','Otros Cargos','Otros Tributos','Monto de redondeo'].reduce((a,k)=>a+(state.totals[k]||0),0))*100)/100;render();status('Proforma calculada. Completa los impuestos e importe en letras según corresponda.')};
async function importFile(file){if(!file)return;if(file.size>30*1024*1024){status('El archivo supera 30 MB. Selecciona un PDF más pequeño.','error');return}status('Leyendo '+file.name+'…');$('download').disabled=true;try{let bytes=new Uint8Array(await file.arrayBuffer());let doc=await pdfjs.getDocument({data:bytes.slice(),useSystemFonts:true,isEvalSupported:false}).promise;let lines=[];for(let n=1;n<=doc.numPages;n++){const p=await doc.getPage(n);lines.push(...linesFromItems((await p.getTextContent()).items))}if(!lines.length)throw Error('El PDF no contiene texto legible. Es un escaneo: completa los datos manualmente.');const parsed=parseLines(lines);state={...empty(),...parsed,totals:{...Object.fromEntries(labels.map(l=>[l,undefined])),...parsed.totals}};sourceBytes=bytes;sourceName=file.name;qrBytes=null;$('qr').value='';$('raw').textContent=lines.join('\n');render();status(parsed.warnings.length?parsed.warnings.join(' '):'Datos extraídos. Revisa la información y descarga tu PDF.',parsed.warnings.length?'error':'success');await doc.destroy()}catch(e){status(e.message||'No se pudo leer el PDF. Prueba con el archivo descargado de SUNAT.','error')}finally{$('download').disabled=false}}
$('file').onchange=e=>importFile(e.target.files[0]);$('drop').ondragover=e=>{e.preventDefault();$('drop').classList.add('over')};$('drop').ondragleave=()=>$('drop').classList.remove('over');$('drop').ondrop=e=>{e.preventDefault();$('drop').classList.remove('over');importFile(e.dataTransfer.files[0])};
$('qr').onchange=async e=>{let f=e.target.files[0];if(!f){qrBytes=null;return}if(!['image/png','image/jpeg'].includes(f.type)){status('El QR debe ser una imagen PNG o JPG.','error');return}qrBytes=new Uint8Array(await f.arrayBuffer());qrType=f.type;status('Imagen QR incorporada al diseño.')};
async function generate(){if(!state.client||!state.series||!state.date||!state.items.length||state.items.some(i=>!i.description)||state.totals['Importe Total']===undefined){status('Completa cliente, número, fecha, descripciones e importe total antes de descargar.','error');return null}if(state.type!=='Proforma'&&(!state.ruc||!state.clientDoc)){status('Completa el RUC del emisor y el documento del cliente.','error');return null}
 const {PDFDocument,StandardFonts,rgb}=window.PDFLib;const pdf=await PDFDocument.create();const regular=await pdf.embedFont(StandardFonts.Helvetica),bold=await pdf.embedFont(StandardFonts.HelveticaBold);const navy=rgb(.08,.14,.21),gray=rgb(.39,.44,.50),pale=rgb(.95,.96,.97),red=rgb(.88,.09,.15);const logo=await pdf.embedPng(await(await fetch('./logo.png')).arrayBuffer());let page,y,pageNo=0;
 const safe=t=>String(t??'').replace(/[–—]/g,'-').replace(/[^\x20-\x7E\xA0-\xFF\n]/g,'');const text=(x,yy,t,size=9,font=regular,color=navy)=>page.drawText(safe(t),{x,y:yy,size,font,color});const right=(x,yy,t,size=9,font=regular,color=navy)=>text(x-font.widthOfTextAtSize(safe(t),size),yy,t,size,font,color);
 const wrap=(t,w,size=9,font=regular)=>{let result=[],line='';for(const word of safe(t).split(/\s+/)){if(font.widthOfTextAtSize((line+' '+word).trim(),size)>w&&line){result.push(line);line=word}else line=(line+' '+word).trim()}if(line)result.push(line);return result};
 function newPage(){page=pdf.addPage([595.28,841.89]);pageNo++;page.drawRectangle({x:0,y:832,width:596,height:10,color:navy});page.drawRectangle({x:36,y:832,width:70,height:10,color:red});page.drawImage(logo,{x:36,y:739,width:228,height:76});page.drawRectangle({x:359,y:731,width:200,height:76,borderColor:rgb(.82,.86,.89),borderWidth:1});text(371,786,'RUC '+state.ruc,11,bold);text(371,765,state.type==='Factura'?'FACTURA ELECTRÓNICA':state.type==='Boleta'?'BOLETA DE VENTA ELECTRÓNICA':'PROFORMA',9,bold);text(371,743,state.series,16,bold);text(36,714,state.issuer,11,bold);let a=wrap(state.address,523);a.forEach((l,i)=>text(36,698-i*12,l));text(36,698-a.length*12,state.city);text(36,650,'COPIAS / PLOTEOS / IMPRESIONES · AL POR MAYOR Y MENOR',8,bold);text(36,26,'Grafiplot Vasquez · '+pageNo,7,regular,gray);y=627}
 function need(h){if(y-h<75)newPage()}
 newPage();page.drawRectangle({x:36,y:533,width:523,height:90,color:pale});text(49,604,'CLIENTE / RAZÓN SOCIAL',7,bold,gray);wrap(state.client,305,11,bold).forEach((l,i)=>text(49,587-i*13,l,11,bold));text(49,553,'RUC / DNI: '+state.clientDoc);text(378,604,'FECHA DE EMISIÓN',7,bold,gray);text(378,588,state.date);text(378,566,'PAGO: '+state.payment);text(378,551,'MONEDA: '+state.currency);y=512;
 if(state.establishment){text(36,y,'ESTABLECIMIENTO DEL EMISOR',7,bold,gray);y-=13;for(const l of wrap(state.establishment,523)){text(36,y,l);y-=12}y-=10}
 const tableHead=()=>{need(34);page.drawRectangle({x:36,y:y-25,width:523,height:25,color:navy});for(const [x,l] of [[42,'Ítem'],[68,'Cant.'],[114,'Medida'],[175,'Descripción'],[412,'Valor unit.'],[499,'Importe']])text(x,y-16,l,8,bold,rgb(1,1,1));y-=25};tableHead();state.items.forEach((i,n)=>{const desc=wrap(i.description,224,9);const h=Math.max(30,desc.length*12+14);if(y-h<85){newPage();tableHead()}page.drawRectangle({x:36,y:y-h,width:523,height:h,color:n%2===0?pale:rgb(1,1,1)});text(42,y-18,n+1,8);text(68,y-18,i.qty,8);text(114,y-18,i.unit,8);desc.forEach((l,k)=>text(175,y-18-k*12,l));right(477,y-18,money(i.price));right(550,y-18,money(i.amount));y-=h});y-=24;
 if(state.observation){need(50);text(36,y,'OBSERVACIÓN / CONDICIONES',7,bold,gray);y-=15;for(const l of wrap(state.observation,523)){need(15);text(36,y,l);y-=13}y-=15}
 need(290);const start=y;text(36,y,'OPERACIONES GRATUITAS',7,bold,gray);text(36,y-17,(state.currency==='SOLES'?'S/ ':'US$ ')+money(state.free));for(let n=0;n<state.items.length;n++)if(state.items[n].icbper){text(36,y-36,'ICBPER de ítem '+(n+1)+': '+money(state.items[n].icbper));break}
 const symbol=state.currency==='SOLES'?'S/ ':'US$ ';for(const l of labels.filter(l=>l!=='Importe Total')){text(335,y,l);right(550,y,state.totals[l]===undefined?'Sin dato':symbol+money(state.totals[l]));y-=17}page.drawRectangle({x:325,y:y-32,width:234,height:34,color:navy});text(337,y-19,'IMPORTE TOTAL',10,bold,rgb(1,1,1));right(547,y-20,symbol+money(state.totals['Importe Total']),18,bold,rgb(1,1,1));y-=57;for(const l of wrap(state.words||'Importe en letras: no consignado.',523,10,bold)){need(15);text(36,y,l,10,bold);y-=14}y-=20;if(y<100)newPage();
 if(state.type==='Proforma'){text(36,y,'PROFORMA - NO ES COMPROBANTE DE PAGO',9,bold);text(36,y-17,'Cotización comercial. No acredita pago ni sustenta crédito fiscal.',8,regular,gray)}else{if(qrBytes){const im=qrType==='image/png'?await pdf.embedPng(qrBytes):await pdf.embedJpg(qrBytes);page.drawImage(im,{x:36,y:y-55,width:64,height:64})}else{page.drawRectangle({x:36,y:y-55,width:64,height:64,borderColor:rgb(.82,.86,.89),borderWidth:1});text(56,y-17,'QR',11,bold,gray);text(40,y-38,'No incorporado',7,regular,gray)}const legend=sourceBytes?`Esta es una representación impresa de la ${state.type==='Factura'?'factura electrónica':'boleta de venta electrónica'}, generada en el Sistema de SUNAT.`:'BORRADOR. Emitir en SUNAT o en un sistema autorizado.';wrap(legend,440,8).forEach((l,i)=>text(112,y-i*12,l,8));text(112,y-34,sourceBytes?'Rediseño. Consulta el comprobante original en las páginas anexas.':'Este borrador no constituye una emisión electrónica.',8,regular,gray)}
 if(sourceBytes){const original=await PDFDocument.load(sourceBytes);const pages=await pdf.copyPages(original,original.getPageIndices());pages.forEach(p=>pdf.addPage(p))}pdf.setTitle('Grafiplot · '+state.type+' '+state.series);pdf.setAuthor(state.issuer);const bytes=await pdf.save();let url=URL.createObjectURL(new Blob([bytes],{type:'application/pdf'})),a=document.createElement('a');a.href=url;a.download=('Grafiplot_'+state.type+'_'+state.series).replace(/[^a-zA-Z0-9_\-]/g,'_')+'.pdf';a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);status('PDF descargado con el diseño Grafiplot.','success');return {filename:a.download,pages:pdf.getPageCount()}}
$('download').onclick=async()=>{$('download').disabled=true;try{await generate()}catch(e){status('No se pudo generar el PDF: '+e.message,'error')}finally{$('download').disabled=false}};
render();
if(document.modelContext?.registerTool){try{document.modelContext.registerTool({name:'read_document',title:'Leer documento actual',description:'Devuelve los datos del documento que se está revisando.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:()=>JSON.parse(JSON.stringify(state))});document.modelContext.registerTool({name:'stage_customer',title:'Completar cliente',description:'Actualiza el cliente en el formulario visible; no descarga ni emite un comprobante.',inputSchema:{type:'object',properties:{client:{type:'string'},clientDoc:{type:'string'}},required:['client','clientDoc'],additionalProperties:false},execute:i=>{if(typeof i.client!=='string'||typeof i.clientDoc!=='string'||!i.client.trim())throw Error('Cliente inválido');state.client=i.client;state.clientDoc=i.clientDoc;render();return {client:state.client,clientDoc:state.clientDoc}}})}catch{}}
