export const defaultIssuer={issuer:'VASQUEZ PALPA ROY RONAL',ruc:'10712451284',address:'JR. MONSEÑOR SARDINAS 600 URB. CAYHUAYNA',city:'PILLCO MARCA - HUANUCO - HUANUCO'};
export function linesFromItems(items){const groups=[];for(const t of items){if(!t.str.trim())continue;const y=t.transform[5];let g=groups.find(g=>Math.abs(g.y-y)<2.2);if(!g){g={y,items:[]};groups.push(g)}g.items.push(t)}return groups.sort((a,b)=>b.y-a.y).map(g=>g.items.sort((a,b)=>a.transform[4]-b.transform[4]).map(t=>t.str).join(' ').replace(/\s+/g,' ').trim())}
const num=s=>Number(String(s).replace(/S\/|,/g,'').trim())||0;
export function parseLines(lines){let text=lines.join('\n'),warnings=[];const find=re=>text.match(re)?.[1]?.trim()||'';
 const type=/BOLETA/i.test(text)?'Boleta':'Factura';const series=find(/\b([EBF]\w{2,3}-\d+)\b/);const rucs=[...text.matchAll(/\b\d{11}\b/g)].map(x=>x[0]);const issuerLine=lines.findIndex(l=>/RUC\s*:/i.test(l));
 let issuer=lines.find(l=>/VASQUEZ/i.test(l))||lines.find(l=>l.length>6&&!/FACTURA|BOLETA|RUC|ELECTRONICA/i.test(l))||'';issuer=issuer.replace(/FACTURA ELECTRONICA.*$/i,'').trim();
 let address=lines.find(l=>/^(JR\.|AV\.|CALLE|JIRON|PSJ\.)/i.test(l))||'';let city=lines.find(l=>/HUANUCO.*HUANUCO|PILLCO MARCA/i.test(l)&&!l.includes('600'))||'';city=city.replace(/\s+[EBF]\w{2,3}-\d+.*$/,'').trim();
 let client=find(/Señor\(es\)\s*:\s*([^\n]+)/i)||find(/Cliente\s*:\s*([^\n]+)/i);let date=find(/Fecha de Emisi[oó]n\s*:\s*(\d{2}\/\d{2}\/\d{4})/i);let payment=find(/Forma de pago\s*:\s*(Contado|Cr[eé]dito)/i);let currency=find(/Tipo de Moneda\s*:\s*(SOLES|D[OÓ]LARES)/i)||'SOLES';
 let items=[];const begin=lines.findIndex(l=>/Cantidad.*Descripci[oó]n/i.test(l));const end=lines.findIndex((l,i)=>i>begin&&/Sub Total Ventas|Subtotal|Valor de Venta de Operaciones|SON:/i.test(l));
 if(begin>=0){for(const l of lines.slice(begin+1,end<0?undefined:end)){const m=l.match(/^(\d+(?:\.\d+)?)\s+(UNIDAD|UNIDADES|SERVICIO|NIU|ZZ|M2|METRO|KG)\s+(.+?)\s+(\d[\d,]*\.\d{2,})\s+(\d[\d,]*\.\d{2})$/i);if(m)items.push({qty:num(m[1]),unit:m[2],description:m[3],price:num(m[4]),icbper:num(m[5]),amount:Math.round(num(m[1])*num(m[4])*100)/100});else if(l.trim())warnings.push('Revisa el detalle: una fila no pudo interpretarse automáticamente.')}}
 const labels=['Sub Total Ventas','Anticipos','Descuentos','Valor Venta','ISC','IGV','ICBPER','Otros Cargos','Otros Tributos','Monto de redondeo','Importe Total'];let totals={};for(const label of labels){const l=lines.find(l=>new RegExp('^'+label+'\\s*:','i').test(l));if(l){const m=l.match(/S\/\s*([\d,]+\.\d{2})/);if(m)totals[label]=num(m[1])}}
 if(!items.length)warnings.push('No se detectaron ítems. Completa la tabla antes de descargar.');if(!client||!date||!series||rucs.length<2||totals['Importe Total']===undefined)warnings.push('Faltan datos del comprobante: revisa los campos y los totales.');
 let establishment='';const ei=lines.findIndex(l=>/Establecimiento del Emisor/i.test(l));if(ei>=0){let start=ei;if(ei>0&&/^(JR\.|AV\.|CALLE)/i.test(lines[ei-1]))start=ei-1;let end=lines.findIndex((l,i)=>i>ei&&/Tipo de Moneda|Observaci[oó]n|Cantidad/i.test(l));establishment=lines.slice(start,end<0?ei+1:end).join(' ').replace(/Establecimiento del Emisor\s*:/i,'').replace(/\s+/g,' ').trim()}const clientDoc=rucs.find(r=>r!==rucs[0])||find(/DNI\s*:\s*(\d{8})/i);const words=find(/(SON:\s*[^\n]+)/i);const free=num(find(/Valor de Venta de Operaciones Gratuitas\s*:\s*S\/\s*([\d,]+\.\d{2})/i));
 return {type,series,ruc:rucs[0]||'',issuer,address,city,client,clientDoc,date,payment,currency,items,totals,words,free,warnings,establishment,observation:''};}
